---
platform: linux

image_resource:
  type: docker-image
  source: {repository: cloudfoundrylondon/backup-and-restore}

inputs:
- name: version
- name: backup-and-restore-sdk-release

outputs:
- name: backup-and-restore-sdk-release-build

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:

run:
  path: backup-and-restore-sdk-release/ci/scripts/create-release.sh
