---
platform: linux

image_resource:
  type: docker-image
  source: {repository: cloudfoundrylondon/backup-and-restore}

inputs:
- name: backup-and-restore-sdk-release
  path: src/github.com/pivotal-cf/backup-and-restore-sdk-release
- name: bosh-backup-and-restore-meta

run:
  path: src/github.com/pivotal-cf/backup-and-restore-sdk-release/ci/scripts/system.sh

params:
  TEAM_GPG_KEY:
  BOSH_CLIENT_SECRET:
  BOSH_CLIENT:
  POSTGRES_PASSWORD:
