
[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "~1.3.1"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "~1.1.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.12.33"
