
[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "~1.3.1"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "~1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/pivotal-cf-experimental/go-binmock"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[prune]
  go-tests = true
  unused-packages = true
