---
name: ((deployment-name))

releases:
- name: backup-and-restore-sdk
  version: set-in-ci

stemcells:
- alias: xenial
  os: ubuntu-xenial
  version: set-in-ci

instance_groups:
- name: database-backup-restorer
  instances: 1
  vm_type: small
  persistent_disk_type: 10GB
  stemcell: xenial
  networks:
  - name: default
  jobs:
  - name: database-backup-restorer
    release: backup-and-restore-sdk
  azs: [z1]

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 30000
  update_watch_time: 30000
