# Copyright (C) 2017-Present Pivotal Software, Inc. All rights reserved.
#
# This program and the accompanying materials are made available under
# the terms of the under the Apache License, Version 2.0 (the "License”);
# you may not use this file except in compliance with the License.
#
# You may obtain a copy of the License at
# http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# See the License for the specific language governing permissions and
# limitations under the License.

---
name: ((deployment-name))

releases:
- name: backup-and-restore-sdk
  version: latest

stemcells:
- alias: xenial
  os: ubuntu-xenial
  version: latest

instance_groups:
- name: gcs-backuper
  instances: 1
  vm_type: small
  persistent_disk_type: 10GB
  stemcell: xenial
  update:
    serial: true
  networks:
  - name: default
  azs: [z1]
  jobs:
  - name: gcs-blobstore-backup-restorer
    release: backup-and-restore-sdk
    properties:
      enabled: true
      buckets:
        droplets:
          bucket_name: ((gcs-bucket-name))
          backup_bucket_name: ((gcs-backup-bucket-name))
          gcp_service_account_key: ((gcp-service-account-key))
- name: gcs-restore-to-clone-bucket
  instances: 1
  vm_type: small
  persistent_disk_type: 10GB
  stemcell: xenial
  update:
    serial: true
  networks:
  - name: default
  azs: [z1]
  jobs:
  - name: gcs-blobstore-backup-restorer
    release: backup-and-restore-sdk
    properties:
      enabled: true
      buckets:
        droplets:
          name: ((gcs-clone-bucket-name))
          gcp_service_account_key: ((gcp-service-account-key))

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 30000
  update_watch_time: 30000
