# Copyright (C) 2017-Present Pivotal Software, Inc. All rights reserved.
#
# This program and the accompanying materials are made available under
# the terms of the under the Apache License, Version 2.0 (the "License”);
# you may not use this file except in compliance with the License.
#
# You may obtain a copy of the License at
# http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# See the License for the specific language governing permissions and
# limitations under the License.

---
name: s3-backuper-local-test

releases:
- name: backup-and-restore-sdk
  version: latest

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: s3-unversioned-backuper
  azs: [z1]
  instances: 1
  vm_type: small
  persistent_disk_type: fifty
  stemcell: trusty
  update:
    serial: true
  networks:
  - name: concourse
  jobs:
  - name: s3-unversioned-blobstore-backup-restorer
    release: backup-and-restore-sdk
    properties:
      enabled: true
      buckets:
        my_bucket:
          name: bbr-system-test-s3-unversioned-bucket
          region: eu-west-1
          aws_access_key_id: ((aws-access-key))
          aws_secret_access_key: ((aws-secret-access-key))
          backup:
            name: bbr-system-test-s3-unversioned-backup-bucket
            region: us-east-1

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 30000
  update_watch_time: 30000
